# Generated by Django 6.0.3 on 2026-03-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_student_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='spassword',
            field=models.CharField(default='hello', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='tpassword',
            field=models.CharField(default='hii', max_length=15),
            preserve_default=False,
        ),
    ]
