# Generated by Django 6.0.3 on 2026-04-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_spassword_trainer_tpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='hii hlo', max_length=200),
            preserve_default=False,
        ),
    ]
