# Generated by Django 6.0.3 on 2026-04-02 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cid',
            field=models.ForeignKey(default=1001, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
            preserve_default=False,
        ),
    ]
