# Generated by Django 6.0.3 on 2026-04-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cid',
        ),
    ]
