# Generated by Django 6.0.3 on 2026-04-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_student_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
    ]
