# Generated by Django 6.0.3 on 2026-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_student_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.CharField(default='hlo'),
            preserve_default=False,
        ),
    ]
