# Generated by Django 6.0.3 on 2026-04-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_course_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tid',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='cid',
        ),
        migrations.AddField(
            model_name='student',
            name='cid',
            field=models.ManyToManyField(to='app.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='tid',
            field=models.ManyToManyField(to='app.trainer'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='cid',
            field=models.ManyToManyField(to='app.course'),
        ),
    ]
