# Generated by Django 6.0.3 on 2026-04-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_student_cid_remove_student_tid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='url',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='hii', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='dateofjoined',
            field=models.DateField(auto_now_add=True, default='2026-02-28'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='duraion',
            field=models.CharField(default='3 months', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=8),
            preserve_default=False,
        ),
    ]
