# Generated by Django 6.0.3 on 2026-04-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_course_url_course_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
