# Generated by Django 6.0.3 on 2026-04-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_course_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='duraion',
            new_name='duration',
        ),
    ]
