# Generated by Django 6.0.3 on 2026-04-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_duraion_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='experience',
            field=models.CharField(default='5 years', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='specializtion',
            field=models.CharField(default='python', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='temail',
            field=models.EmailField(default='abc@gmail.com', max_length=30),
            preserve_default=False,
        ),
    ]
