# Generated by Django 6.0.3 on 2026-04-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_trainer_experience_trainer_specializtion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semail',
            field=models.CharField(default='abc@gmail.com', max_length=30),
            preserve_default=False,
        ),
    ]
