# Generated by Django 6.0.3 on 2026-04-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_student_semail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dateofjoined',
        ),
        migrations.AddField(
            model_name='student',
            name='dateofjoined',
            field=models.DateField(auto_now_add=True, default='2026-4-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='dateofjoined',
            field=models.DateField(auto_now_add=True, default='2026-4-27'),
            preserve_default=False,
        ),
    ]
