# Generated by Django 6.0.3 on 2026-05-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_course_dateofjoined_student_dateofjoined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='tid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
