# Generated by Django 6.0.3 on 2026-05-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_trainer_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phoneno',
            field=models.IntegerField(default=987654321, max_length=10),
            preserve_default=False,
        ),
    ]
