# Generated by Django 6.0.3 on 2026-05-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_student_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
