# Generated by Django 6.0.3 on 2026-05-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_student_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sname',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='jai shree raam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='raam', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneno',
            field=models.IntegerField(),
        ),
    ]
