# Generated by Django 6.0.3 on 2026-05-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_sname_student_fullname_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dateofbirth',
            field=models.DateField(default='2004-02-08'),
            preserve_default=False,
        ),
    ]
