# Generated by Django 6.0.3 on 2026-05-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_student_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='hii', max_length=200),
            preserve_default=False,
        ),
    ]
