# Generated by Django 6.0.5 on 2026-05-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='semail',
            field=models.EmailField(max_length=30),
        ),
    ]
