# Generated by Django 6.0.5 on 2026-05-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='media/default/aiml1.png', upload_to='media/student_images'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='profile_pic',
            field=models.ImageField(default='media/default/aiml1.png', upload_to='media/trainer_images'),
        ),
    ]
