# Generated by Django 6.0.5 on 2026-05-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_student_profile_pic_alter_trainer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneno',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semail',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='temail',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
