# Generated by Django 6.0.5 on 2026-05-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_student_phoneno_alter_student_semail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semail',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='temail',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
