# Generated by Django 6.0.5 on 2026-05-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_student_semail_alter_trainer_temail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cimage',
            field=models.ImageField(default='static/images/Python.png', upload_to='course_images'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
