# Generated by Django 6.0.5 on 2026-05-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_course_cimage_alter_course_cname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cimage',
            field=models.ImageField(upload_to='course_images'),
        ),
    ]
