# Generated by Django 6.0.5 on 2026-05-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_course_cimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='spassword',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='tpassword',
            field=models.CharField(),
        ),
    ]
