# Generated by Django 6.0.5 on 2026-05-25 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_student_spassword_alter_trainer_tpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='course_videos')),
                ('pdf', models.FileField(upload_to='course_pdfs')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
    ]
