# Generated by Django 6.0.5 on 2026-05-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_cursecontent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurseContent',
            new_name='CourseContent',
        ),
    ]
