# Generated by Django 6.0.5 on 2026-05-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_rename_cursecontent_coursecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='course_pdfs'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos'),
        ),
    ]
