# Generated by Django 6.0.5 on 2026-05-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_coursecontent_pdf_alter_coursecontent_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default='2026-05-26'),
            preserve_default=False,
        ),
    ]
