# Generated by Django 6.0.5 on 2026-05-27 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_coursecontent_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trainer'),
        ),
    ]
