# Generated by Django 6.0.5 on 2026-05-27 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_coursecontent_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trainer'),
        ),
    ]
