# Generated by Django 6.0.5 on 2026-05-31 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_progress_content_alter_progress_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coursecontent'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('student', 'content')},
        ),
    ]
