# Generated by Django 6.0.5 on 2026-06-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_patyment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patyment',
            new_name='Payment',
        ),
    ]
