# Generated by Django 6.0.6 on 2026-06-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_rename_patyment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='pdf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
